### ISSUE TITLE
Grape 0.16 support

### ISSUE THREAD

**Issue by syntaxTerr0r** [aai/grape-appsignal#5]
The gem raise this error when used with grape 0.16.2:

``` ruby
undefined method `settings' for #<#<Class:0x007fece36cc7d0>:0x007fece9da5600>
```

I suppose grape changed its middleware internal API.

**Comment by thijsc** [comment]
We've ported this integration to our main gem (starting at version 1.1). See these docs on how to set it up: http://docs.appsignal.com/getting-started/supported-frameworks.html#grape

I'll make a pull to add a note about this to the readme in this repo.

**Comment by syntaxTerr0r** [comment]
I missed the news, thanks!

**Comment by thijsc** [comment]
Updated the readme in 3aecb804f796909edb2bdc0a70d09b0f2631d052
